### PR TITLE
Pk/morefix

### PR DESCRIPTION
**Pull request by petrkr**
More fixes in compilation..
By the way. file `tuxtxt.c` is encoded by some codepage, resave with UTF-8 will do some mess with special chars. I can not find which encoding was used at original file to re-encode it to UTF-8.

For now I let it be like that, but whenever I will see GUI part, I will try to figure out right encoding... 

it's because of those chars https://github.com/OpenVisionE2/tuxtxt/blob/master/tuxtxt/tuxtxt.c#L927

### CODE REVIEW

**Comment by persianpros** [comment]
@petrkr 

Thanks my friend :+1: 

I just fixed some warnings in enigma2 so please check the remaining warnings ...

P.S. let me know what you want to change exactly, I can do it with sed without change the codepage.

**Comment by petrkr** [comment]
I did that in 'vim' also without cp change. I just suggest to understand what that chars do and resave it to 21st century and recode to utf-8 later.. it's just for refactor TODO.

**Comment by petrkr** [comment]
I did that in 'vim' also without cp change. I just suggest to understand what that chars do and resave it to 21st century and recode to utf-8 later.. it's just for refactor TODO.

**Comment by petrkr** [comment]
Also there are few warnings from autoreconf in tuxtxt too, but with those still do not know how to fix them. For now just skipping and will look later for other packages.

**Pull request merged**
